# Generates plots from the results generated by the Disease.java program.

import pylab, sys
import matplotlib.cm as cm
from matplotlib.colors import normalize as Norm

def main(args):
    if len(args) != 3:
        print "Usage: python plots.py <results file> <start time> <end time>"
        sys.exit()
    fh = open(args[0], "r")
    N, T, step = map(int, fh.readline().split())
    ts = int(args[1]) / step
    td = int(args[2]) / step + step
    x = range(0, T + step, step)
    sl = []
    il = []
    rl = []
    cl = []
    m = []
    vmin = 1.0
    vmax = 0.0
    for line in fh.readlines():
        line = line.split()
        s = int(line[0])
        i = int(line[1])
        r = int(N - s - i)
        c = float(line[2])
        sl.append(s / (1.0 * N))
        il.append(i / (1.0 * N))
        rl.append(r / (1.0 * N))
        cl.append(c)
        l = [1.0 for j in range(0, 101)]
        for item in line[3:]:
            a, b = map(int, item.split(":"))
            t = 1 - b * 1.0 / N
            if t < vmin and t > 0:
                vmin = t
            if t > vmax and t < 1:
                vmax = t
            l[a] = t
        m.append(l)
    fh.close()

    # Mean virulence over the last 10% of the generations.
    last = int(T * 0.1)
    i = T / step - last / step
    l = cl[i:]
    final_c_mean = sum(l) / len(l) 

    # Time evolution of the number of people in susceptible, infected, 
    # and recovered states.
    pylab.figure(1, figsize = (7, 4.5), dpi = 500)
    pylab.xlabel(r"$t$")
    pylab.ylabel(r"$s, x, r$")
    pylab.plot(x[ts:td], sl[ts:td], "#000000", alpha = 0.6, linewidth = 2.0)
    pylab.plot(x[ts:td], il[ts:td], "#FF0000", alpha = 0.6, linewidth = 2.0)
    pylab.plot(x[ts:td], rl[ts:td], "#0000FF", alpha = 0.6, linewidth = 2.0)
    pylab.legend((r"$s$", r"$x$", r"$r$"), 'best', shadow = False)
    pylab.xlim(int(args[1]), int(args[2]))
    pylab.ylim(0, 1)
    ax = pylab.gca()
    ax.xaxis.major.formatter.set_powerlimits((0,0))
    pylab.savefig("plot1.pdf", format = "pdf")
    pylab.close(1)

    # Time evolution of the mean virulence.
    pylab.figure(2, figsize = (7, 4.5), dpi = 500)
    pylab.xlabel(r"$t$")
    pylab.ylabel(r"$\bar{c}$")
    pylab.plot(x[ts:td], cl[ts:td], "#000000", alpha = 0.6, linewidth = 2.0)
    pylab.figtext(0.82, 0.85, r"$\bar{c}_\infty = %4.3f$" %(final_c_mean), 
                  ha = 'center', va = 'center', bbox = dict(facecolor = 'white', edgecolor = 'black'))
    pylab.xlim(int(args[1]), int(args[2]))
    pylab.ylim(0, 1)
    ax = pylab.gca()
    ax.xaxis.major.formatter.set_powerlimits((0,0))
    pylab.savefig("plot2.pdf", format = "pdf")
    pylab.close(2)

if __name__ == "__main__":
    main(sys.argv[1:])
