# Generates plots from the results generated by the Discrete.java program.

import pylab, sys

def main(args):
    if len(args) != 3:
        print "Usage: python plots.py <results file> <start time> <end time>"
        sys.exit()
    fh = open(args[0], "r")
    l = fh.readline().split()
    N = int(l[0])
    T = int(l[1])
    step = int(l[2])
    mean_c = float(l[3])
    ts = int(args[1]) / step
    td = int(args[2]) / step + step
    x = range(0, T + step, step)
    cl = []
    for line in fh.readlines():
        c = float(line)
        cl.append(c)
    fh.close()

    # Time evolution of the fraction of cooperators.
    pylab.figure(1, figsize = (7, 4.5), dpi = 500)
    pylab.xlabel(r"$t$")
    pylab.ylabel(r"$x$")
    pylab.plot(x[ts:td], cl[ts:td], "#000000", alpha = 0.6, linewidth = 2.0)
    pylab.figtext(0.82, 0.85, r"$x_\infty = %4.3f$" %(mean_c), 
                  ha = 'center', va = 'center', 
                  bbox = dict(facecolor = 'white', edgecolor = 'black'))
    pylab.xlim(int(args[1]), int(args[2]))
    pylab.ylim(0, 1)
    ax = pylab.gca()
    ax.xaxis.major.formatter.set_powerlimits((0,0))
    pylab.savefig("plot.pdf", format = "pdf")
    pylab.close(1)

if __name__ == "__main__":
    main(sys.argv[1:])
